version: '3.7'

services:
  app:
    environment:
      - NODE_ENV=production
      - ENV_PATH=../../../run/secrets/.env
    build: .
    ports:
      - 3000:3000
    secrets:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db

volumes:
  db-data:

secrets:
  .env:
    file: ./.env
